// Generated by GitHub Copilot - Sep-27-2026
import { act, cleanup, fireEvent, render, renderHook, screen, waitFor } from '@testing-library/react'
import { ModelType, prebuiltAppConfig, type WebWorkerMLCEngine } from '@mlc-ai/web-llm'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import App from '../src/App'
import { models, useModelLoader, type LoadedModel } from '../src/hooks/useModelLoader'
import { useLLMCompletion } from '../src/hooks/useLLMCompletion'

const { createEngine } = vi.hoisted(() => ({ createEngine: vi.fn() }))
/** 公式モデル設定は実物を使い、GPU・ネットワーク処理だけを差し替える。 */
vi.mock('@mlc-ai/web-llm', async (importOriginal) => ({
  ...await importOriginal<typeof import('@mlc-ai/web-llm')>(),
  CreateWebWorkerMLCEngine: createEngine,
}))

/** ネットワークとGPUを使わずWorkerのライフサイクルを検証する。 */
class FakeWorker extends EventTarget {
  static instances: FakeWorker[] = []
  terminate = vi.fn()
  /** テスト対象のWorker生成を記録する。 */
  constructor() {
    super()
    FakeWorker.instances.push(this)
  }
}

/** 解決タイミングをテストから制御する。 */
function deferred<T>() {
  let resolve!: (value: T) => void
  let reject!: (reason: unknown) => void
  const promise = new Promise<T>((done, fail) => { resolve = done; reject = fail })
  return { promise, resolve, reject }
}

/** 実APIのうちテストで必要なメソッドだけを提供する。 */
function fakeEngine() {
  return {
    chat: { completions: { create: vi.fn().mockResolvedValue({ choices: [{ message: { content: '回答' } }] }) } },
    unload: vi.fn().mockResolvedValue(undefined),
    interruptGenerate: vi.fn(),
  }
}

/** 読込済み状態のテスト用データを生成する。 */
function session(engine = fakeEngine()): LoadedModel {
  return { engine: engine as unknown as WebWorkerMLCEngine, model: structuredClone(models[0]), signal: new AbortController().signal, running: false }
}

beforeEach(() => {
  vi.clearAllMocks()
  FakeWorker.instances = []
  vi.stubGlobal('Worker', FakeWorker)
  vi.stubGlobal('isSecureContext', true)
  Object.defineProperty(navigator, 'gpu', { configurable: true, value: {} })
  createEngine.mockResolvedValue(fakeEngine())
})

afterEach(() => {
  cleanup()
  vi.unstubAllGlobals()
  Reflect.deleteProperty(navigator, 'gpu')
})

describe('useModelLoader', () => {
  /** 全選択肢が独自設定なしで公式モデルIDによって読み込まれることを検証する。 */
  it('公式一覧の全テキストモデルをappConfigなしで読み込む', async () => {
    expect(models).toEqual(prebuiltAppConfig.model_list.filter(
      (model) => (model.model_type ?? ModelType.LLM) === ModelType.LLM,
    ))
    expect(models.length).toBeGreaterThan(5)
    expect(models.some((model) => model.model_type === ModelType.embedding)).toBe(false)
    const { result } = renderHook(useModelLoader)
    for (const model of models) {
      expect(prebuiltAppConfig.model_list).toContain(model)
      await act(() => result.current.load(model))
      expect(createEngine).toHaveBeenLastCalledWith(
        FakeWorker.instances.at(-1),
        model.model_id,
        { initProgressCallback: expect.any(Function) },
      )
      expect(result.current.status).toBe('ready')
      expect(result.current.loadedModel?.model).not.toHaveProperty('inference')
    }
  })

  it('未選択では何もせず、同一IDを再利用して空実行しない', async () => {
    const engine = fakeEngine()
    createEngine.mockResolvedValue(engine)
    const { result } = renderHook(useModelLoader)
    await act(() => result.current.load(null))
    expect(createEngine).not.toHaveBeenCalled()
    await act(() => result.current.load(models[0]))
    await act(() => result.current.load({ model_id: models[0].model_id }))
    expect(createEngine).toHaveBeenCalledTimes(1)
    expect(engine.chat.completions.create).not.toHaveBeenCalled()
    expect(result.current.status).toBe('ready')
    expect(result.current.progressPct).toBe(100)
  })

  it('異なるモデルはunloadとWorker終了後に読み込む', async () => {
    const engine = fakeEngine()
    const release = deferred<void>()
    engine.unload.mockReturnValue(release.promise)
    createEngine.mockResolvedValue(engine)
    const { result } = renderHook(useModelLoader)
    await act(() => result.current.load(models[0]))
    let change!: Promise<void>
    act(() => { change = result.current.load(models[1]) })
    expect(engine.unload).toHaveBeenCalledOnce()
    expect(createEngine).toHaveBeenCalledTimes(1)
    expect(FakeWorker.instances[0].terminate).not.toHaveBeenCalled()
    await act(async () => { release.resolve(); await change })
    expect(FakeWorker.instances[0].terminate).toHaveBeenCalledOnce()
    expect(createEngine).toHaveBeenCalledTimes(2)
    expect(result.current.loadedModel?.model.model_id).toBe(models[1].model_id)
  })

  it('進捗を反映し、連打で重複読込しない', async () => {
    const pending = deferred<ReturnType<typeof fakeEngine>>()
    createEngine.mockImplementation((_worker, _id, config) => {
      config.initProgressCallback({ progress: 0.45, text: '取得中' })
      return pending.promise
    })
    const { result } = renderHook(useModelLoader)
    let load!: Promise<void>
    act(() => { load = result.current.load(models[0]); void result.current.load(models[0]) })
    await waitFor(() => expect(result.current.progressPct).toBe(45))
    expect(result.current.progressText).toBe('取得中')
    expect(createEngine).toHaveBeenCalledOnce()
    await act(async () => { pending.resolve(fakeEngine()); await load })
  })

  it('読込失敗時にWorkerと保持情報を解放して再試行できる', async () => {
    createEngine.mockRejectedValueOnce(new Error('ダウンロード失敗'))
    const { result } = renderHook(useModelLoader)
    await act(() => result.current.load(models[0]))
    expect(result.current.error).toBe('ダウンロード失敗')
    expect(result.current.loadedModel).toBeNull()
    expect(FakeWorker.instances[0].terminate).toHaveBeenCalledOnce()
    await act(() => result.current.load(models[0]))
    expect(result.current.status).toBe('ready')
  })

  it('Worker自体のエラーで読込の待機を解除する', async () => {
    createEngine.mockReturnValue(new Promise(() => {}))
    const { result } = renderHook(useModelLoader)
    let load!: Promise<void>
    act(() => { load = result.current.load(models[0]) })
    await waitFor(() => expect(FakeWorker.instances).toHaveLength(1))
    await act(async () => { FakeWorker.instances[0].dispatchEvent(new Event('error')); await load })
    expect(result.current.status).toBe('error')
    expect(result.current.loadedModel).toBeNull()
    expect(FakeWorker.instances[0].terminate).toHaveBeenCalledOnce()
  })

  it('読込中のアンマウントでもWorkerを終了する', async () => {
    createEngine.mockReturnValue(new Promise(() => {}))
    const { result, unmount } = renderHook(useModelLoader)
    let load!: Promise<void>
    act(() => { load = result.current.load(models[0]) })
    await waitFor(() => expect(FakeWorker.instances).toHaveLength(1))
    unmount()
    await load
    expect(FakeWorker.instances[0].terminate).toHaveBeenCalledOnce()
  })

  it('非対応ブラウザではWorkerを作成しない', async () => {
    Reflect.deleteProperty(navigator, 'gpu')
    const { result } = renderHook(useModelLoader)
    await act(() => result.current.load(models[0]))
    expect(result.current.error).toContain('WebGPU')
    expect(FakeWorker.instances).toHaveLength(0)
  })
})

describe('useLLMCompletion', () => {
  // Generated by GitHub Copilot - Sep-28-2026
  it.each(['{"type":', '{"type":"object",}', 'null', '[]', '"object"', '123', 'true'])(
    '不正なJSONスキーマでは推論せず、修正後に再実行できる: %s',
    /** 構文エラーと非オブジェクト入力を拒否し、実行状態を変更しない。 */
    async (schemaText) => {
      const engine = fakeEngine()
      const loaded = session(engine)
      const { result } = renderHook(useLLMCompletion)
      await act(() => result.current.complete(loaded, loaded.model, '', '入力', schemaText))
      expect(result.current.error).toContain('JSON')
      expect(engine.chat.completions.create).not.toHaveBeenCalled()
      expect(result.current.isRunning).toBe(false)
      expect(loaded.running).toBe(false)
      expect(result.current.logs).toHaveLength(0)
      const schema = { type: 'object', properties: { answer: { type: 'string' } } }
      await act(() => result.current.complete(loaded, loaded.model, '', '入力', JSON.stringify(schema)))
      expect(result.current.error).toBeNull()
      expect(engine.chat.completions.create).toHaveBeenCalledExactlyOnceWith(expect.objectContaining({
        response_format: { type: 'json_object', schema: JSON.stringify(schema) },
      }))
      expect(result.current.logs[0].json_schema).toEqual(schema)
      expect(loaded.model.json_schema).toBeUndefined()
    },
  )

  // Generated by GitHub Copilot - Sep-28-2026
  it.each(['', '  \n\t '])('空欄では構造化出力を指定しない: %j',
    /** 明示的な空欄はモデル側の既存スキーマより優先する。 */
    async (schemaText) => {
      const engine = fakeEngine()
      const loaded = session(engine)
      loaded.model.json_schema = { type: 'object' }
      const { result } = renderHook(useLLMCompletion)
      await act(() => result.current.complete(loaded, loaded.model, '', '入力', schemaText))
      expect(engine.chat.completions.create.mock.calls[0][0]).not.toHaveProperty('response_format')
      expect(result.current.logs[0].json_schema).toBe('なし')
      expect(loaded.model.json_schema).toEqual({ type: 'object' })
    },
  )

  // Generated by GitHub Copilot - Sep-27-2026
  it.each([
    ['Qwen3-0.6B-q4f16_1-MLC', '<think>検討\n内容</think>\n\n要約', '要約'],
    ['Qwen2.5-1.5B-Instruct-q4f32_1-MLC', '<think>検討</think>要約', '要約'],
    ['Qwen3-0.6B-q4f16_1-MLC', '<think>未完の検討', ''],
    ['Qwen3-0.6B-q4f16_1-MLC', '<think>検討</think>本文<think>再検討</think>末尾', '本文末尾'],
    ['Qwen3-0.6B-q4f16_1-MLC', 'タグのない回答', 'タグのない回答'],
    ['gemma3-1b-it-q4f16_1-MLC', '<think>検討</think>\n回答', '<think>検討</think>\n回答'],
  ])('Qwenの表示だけ思考部分を除去する: %s / %s',
    /** 表示の加工範囲と、ログ内レスポンスの非変更を検証する。 */
    async (modelId, content, expected) => {
      const engine = fakeEngine()
      const loaded = session(engine)
      loaded.model.model_id = modelId
      const response = { choices: [{ message: { content } }] }
      engine.chat.completions.create.mockResolvedValue(response)
      const { result } = renderHook(useLLMCompletion)
      await act(() => result.current.complete(loaded, loaded.model, '', '入力'))
      expect(result.current.answer).toBe(expected)
      expect(result.current.logs[0].RESPONSE).toBe(response)
      expect(result.current.logs[0].RESPONSE?.choices[0].message.content).toBe(content)
    },
  )

  it('未ロード・未選択・異なるモデルでの実行を拒否する', async () => {
    const engine = fakeEngine()
    const loaded = session(engine)
    const { result } = renderHook(useLLMCompletion)
    await act(() => result.current.complete(null, models[0], '', '入力'))
    await act(() => result.current.complete(loaded, null, '', '入力'))
    await act(() => result.current.complete(loaded, models[1], '', '入力'))
    expect(engine.chat.completions.create).not.toHaveBeenCalled()
    expect(result.current.logs).toHaveLength(0)
  })

  it('入力とSchemaと設定のスナップショットを保持し、重複実行を防ぐ', async () => {
    const pending = deferred<unknown>()
    const engine = fakeEngine()
    engine.chat.completions.create.mockReturnValue(pending.promise)
    const loaded = session(engine)
    loaded.model.json_schema = { type: 'object', properties: { answer: { type: 'string' } }, required: ['answer'] }
    const { result } = renderHook(useLLMCompletion)
    let run!: Promise<void>
    act(() => { run = result.current.complete(loaded, models[0], 'JSONで回答', '最初の入力') })
    act(() => { void result.current.complete(loaded, models[0], '変更後', '変更後') })
    loaded.model.json_schema.required = []
    expect(engine.chat.completions.create).toHaveBeenCalledOnce()
    expect(engine.chat.completions.create.mock.calls[0][0]).not.toHaveProperty('model')
    expect(engine.chat.completions.create.mock.calls[0][0].response_format.type).toBe('json_object')
    const response = {
      id: 'test-completion',
      model: models[0].model_id,
      object: 'chat.completion',
      created: 1790470914774,
      choices: [{ index: 0, finish_reason: 'stop', logprobs: null, message: { role: 'assistant', content: '{"answer":"結果"}' } }],
      usage: { prompt_tokens: 20, completion_tokens: 10, total_tokens: 30, extra: { prefill_tokens_per_s: 30, decode_tokens_per_s: 2 } },
    }
    await act(async () => { pending.resolve(response); await run })
    const log = result.current.logs[0]
    expect(log.system_prompt).toBe('JSONで回答')
    expect(log.message).toBe('最初の入力')
    expect(log.json_schema).toMatchObject({ required: ['answer'] })
    expect(log).not.toHaveProperty('model_id')
    expect(log).not.toHaveProperty('answer')
    expect(log.RESPONSE).toEqual(response)
    expect(log).not.toHaveProperty('model')
    expect(log).not.toHaveProperty('label')
    expect(log.inference_settings).toEqual({ temperature: 0.7, top_p: 0.9, max_tokens: 1024 })
    expect(engine.chat.completions.create.mock.calls[0][0]).toMatchObject(log.inference_settings)
    expect(log.started_at).toMatch(/Z$/)
    expect(log.duration_ms).toBeGreaterThanOrEqual(0)
    expect(log.result).toBe('成功')
    expect(result.current.answer).toBe('{"answer":"結果"}')
  })

  it('実行時の推論パラメーターを成功・失敗のログに記録する', async () => {
    const engine = fakeEngine()
    const loaded = session(engine)
    const { result } = renderHook(useLLMCompletion)
    await act(() => result.current.complete(loaded, models[0], '', '1回目'))
    engine.chat.completions.create.mockRejectedValueOnce(new Error('GPUメモリ不足'))
    await act(() => result.current.complete(loaded, models[0], '', '2回目'))
    expect(result.current.logs).toHaveLength(2)
    expect(result.current.logs[0]).toMatchObject({ result: '成功', RESPONSE: { choices: [{ message: { content: '回答' } }] }, error: 'なし', json_schema: 'なし' })
    expect(result.current.logs[1]).toMatchObject({ result: '失敗', RESPONSE: null, message: '2回目', error: 'GPUメモリ不足' })
    for (const [index, log] of result.current.logs.entries()) {
      expect(log.inference_settings).toEqual({ temperature: 0.7, top_p: 0.9, max_tokens: 1024 })
      expect(engine.chat.completions.create.mock.calls[index][0]).toMatchObject(log.inference_settings)
    }
    expect(result.current.isRunning).toBe(false)
  })

  it('Worker停止時には推論を解除して失敗ログを残す', async () => {
    const engine = fakeEngine()
    engine.chat.completions.create.mockReturnValue(new Promise(() => {}))
    const controller = new AbortController()
    const loaded = { ...session(engine), signal: controller.signal }
    const { result } = renderHook(useLLMCompletion)
    let run!: Promise<void>
    act(() => { run = result.current.complete(loaded, models[0], '', '入力') })
    await act(async () => { controller.abort(new Error('Worker停止')); await run })
    expect(result.current.logs[0].error).toBe('Worker停止')
    expect(result.current.isRunning).toBe(false)
    expect(loaded.running).toBe(false)
  })
})

describe('HomeCompoentns', () => {
  // Generated by GitHub Copilot - Sep-28-2026
  /** 入力欄からのスキーマが実行時に検証され、修正後はリクエストへ渡る。 */
  it('JSONスキーマ入力とエラー表示を実行処理に接続する', async () => {
    const engine = fakeEngine()
    createEngine.mockResolvedValue(engine)
    render(<App />)
    const schemaInput = screen.getByRole('textbox', { name: '構造化出力のJSONスキーマ' })
    expect(schemaInput.getAttribute('rows')).toBe('6')
    fireEvent.change(schemaInput, { target: { value: '{invalid' } })
    fireEvent.mouseDown(screen.getByRole('combobox'))
    fireEvent.click(screen.getByRole('option', { name: models[0].model_id }))
    fireEvent.click(screen.getByRole('button', { name: '読込' }))
    await screen.findByRole('button', { name: '実行' })
    fireEvent.click(screen.getByRole('button', { name: '実行' }))
    expect((await screen.findByRole('alert')).textContent).toContain('JSONスキーマを解析できません')
    expect(engine.chat.completions.create).not.toHaveBeenCalled()
    const schema = { type: 'object', properties: { answer: { type: 'string' } } }
    fireEvent.change(schemaInput, { target: { value: JSON.stringify(schema) } })
    fireEvent.click(screen.getByRole('button', { name: '実行' }))
    await waitFor(() => expect(engine.chat.completions.create).toHaveBeenCalledOnce())
    expect(engine.chat.completions.create.mock.calls[0][0].response_format).toEqual({
      type: 'json_object', schema: JSON.stringify(schema),
    })
    await waitFor(() => expect(screen.queryByRole('alert')).toBeNull())
  })

  it('ボタンの状態を切り替え、出力をHTMLでなくテキストとして表示する', async () => {
    const pending = deferred<unknown>()
    const engine = fakeEngine()
    engine.chat.completions.create.mockReturnValue(pending.promise)
    createEngine.mockResolvedValue(engine)
    render(<App />)
    expect((screen.getByRole('button', { name: '読込' }) as HTMLButtonElement).disabled).toBe(true)
    fireEvent.mouseDown(screen.getByRole('combobox'))
    expect(screen.getAllByRole('option')).toHaveLength(models.length + 1)
    fireEvent.click(screen.getByRole('option', { name: 'Qwen2.5-1.5B-Instruct-q4f32_1-MLC' }))
    expect((screen.getByRole('button', { name: '読込' }) as HTMLButtonElement).disabled).toBe(false)
    fireEvent.click(screen.getByRole('button', { name: '読込' }))
    await screen.findByRole('button', { name: '実行' })
    fireEvent.change(screen.getByLabelText('メッセージ'), { target: { value: '開始時の入力' } })
    fireEvent.click(screen.getByRole('button', { name: '実行' }))
    expect((screen.getByRole('button', { name: '実行中…' }) as HTMLButtonElement).disabled).toBe(true)
    fireEvent.change(screen.getByLabelText('メッセージ'), { target: { value: '実行中の編集' } })
    await act(async () => { pending.resolve({ choices: [{ message: { content: '<img src=x onerror=alert(1)>\n**未加工**' } }] }) })
    const output = screen.getByRole('region', { name: '回答テキスト' })
    expect(output.textContent).toBe('<img src=x onerror=alert(1)>\n**未加工**')
    expect(output.querySelector('img')).toBeNull()
    const logRegion = screen.getByRole('region', { name: '実行ログJSON' })
    expect(logRegion.textContent).not.toContain('\n')
    expect(getComputedStyle(logRegion).whiteSpace).toBe('pre')
    const log = JSON.parse(logRegion.textContent!)
    expect(log.message).toBe('開始時の入力')
    fireEvent.click(screen.getByRole('button', { name: '実行' }))
    await waitFor(() => expect(logRegion.textContent!.split('\n')).toHaveLength(2))
    const logs = logRegion.textContent!.split('\n').map((line) => JSON.parse(line))
    expect(logs[0].message).toBe('開始時の入力')
    expect(logs[1].message).toBe('実行中の編集')
    fireEvent.mouseDown(screen.getByRole('combobox'))
    fireEvent.click(screen.getByRole('option', { name: 'Qwen3-0.6B-q4f16_1-MLC' }))
    expect((screen.getByRole('button', { name: '読込' }) as HTMLButtonElement).disabled).toBe(false)
    fireEvent.mouseDown(screen.getByRole('combobox'))
    fireEvent.click(screen.getByRole('option', { name: 'モデルを選択' }))
    expect((screen.getByRole('button', { name: '読込' }) as HTMLButtonElement).disabled).toBe(true)
  })
})