// Generated by GitHub Copilot - Sep-28-2026
import type { ChatCompletion, ChatCompletionRequestNonStreaming } from '@mlc-ai/web-llm'
import { useCallback, useEffect, useRef, useState } from 'react'
import { abortable, errorMessage } from '../utils/async'
import type { LoadedModel, SelectedModel } from './useModelLoader'

export interface CompletionLog {
	started_at: string
	system_prompt: string
	message: string
	inference_settings: Record<'temperature' | 'top_p' | 'max_tokens', number>
	json_schema: Record<string, unknown> | 'なし'
	result: '成功' | '失敗'
	duration_ms: number
	RESPONSE: ChatCompletion | null
	error: string
}

/** Qwenの思考部分は表示から除き、未加工レスポンスと入力全文のログはメモリ内のみで保持する。 */
export function useLLMCompletion() {
	const [answer, setAnswer] = useState('')
	const [logs, setLogs] = useState<CompletionLog[]>([])
	const [isRunning, setIsRunning] = useState(false)
	const [error, setError] = useState<string | null>(null)
	const runningRef = useRef(false)
	const mountedRef = useRef(false)

	useEffect(() => {
		mountedRef.current = true
		return () => { mountedRef.current = false }
	}, [])

	// Generated by GitHub Copilot - Sep-28-2026
	/** JSONの構文とオブジェクト形式を推論前に検証し、開始時点の入力・設定で実行結果を記録する。 */
	const complete = useCallback(async (
		loaded: LoadedModel | null,
		selected: SelectedModel | null,
		systemPrompt: string,
		message: string,
		jsonSchemaText?: string,
	) => {
		if (!mountedRef.current || runningRef.current || !loaded || loaded.running || loaded.signal.aborted
			|| !selected || selected.model_id !== loaded.model.model_id) return

		const model = structuredClone(loaded.model)
		if (jsonSchemaText !== undefined) {
			delete model.json_schema
			if (jsonSchemaText.trim()) {
				try {
					const parsed: unknown = JSON.parse(jsonSchemaText)
					if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
						setError('JSONスキーマはJSONオブジェクト形式で入力してください。')
						return
					}
					model.json_schema = parsed as Record<string, unknown>
				} catch {
					setError('JSONスキーマを解析できません。正しいJSON形式で入力してください。')
					return
				}
			}
		}
		const settings = { temperature: 0.7, top_p: 0.9, max_tokens: 4096 }
		const request: ChatCompletionRequestNonStreaming = {
			messages: [
				...(systemPrompt ? [{ role: 'system' as const, content: systemPrompt }] : []),
				{ role: 'user', content: message },
			],
			...settings,
			stream: false,
			...(model.json_schema ? { response_format: { type: 'json_object' as const, schema: JSON.stringify(model.json_schema) } } : {}),
		}
		const log: CompletionLog = {
			started_at: new Date().toISOString(),
			system_prompt: systemPrompt,
			message,
			inference_settings: settings,
			json_schema: model.json_schema ?? 'なし',
			result: '失敗',
			duration_ms: 0,
			RESPONSE: null,
			error: 'なし',
		}
		runningRef.current = true
		loaded.running = true
		setIsRunning(true)
		setError(null)
		setAnswer('')
		const start = performance.now()
		try {
			const response = await abortable(loaded.engine.chat.completions.create(request), loaded.signal)
			log.duration_ms = performance.now() - start
			log.RESPONSE = response
			log.result = '成功'
			const content = response.choices[0]?.message.content ?? ''
			// 出力上限で閉じタグが欠けた思考部分も隠す。ログのRESPONSEは変更しない。
			const displayText = model.model_id.startsWith('Qwen')
				? content.replace(/<think>[\s\S]*?(?:<\/think>|$)/g, '').trim()
				: content
			if (mountedRef.current) setAnswer(displayText)
		} catch (cause) {
			log.duration_ms = performance.now() - start
			log.error = errorMessage(cause)
			if (mountedRef.current) setError(log.error)
		} finally {
			loaded.running = false
			runningRef.current = false
			if (mountedRef.current) {
				setLogs((previous) => [...previous, log])
				setIsRunning(false)
			}
		}
	}, [])

	// Generated by GitHub Copilot - Sep-27-2026
	/** 回答や実行状態を変更せず、ログ配列だけを空にする。 */
	const clearLogs = () => setLogs([])

	return { answer, logs, isRunning, error, complete, clearLogs }
}
