// Generated by GitHub Copilot - Sep-27-2026
import { ModelType, prebuiltAppConfig, type WebWorkerMLCEngine } from '@mlc-ai/web-llm'
import { useCallback, useEffect, useRef, useState } from 'react'
import { abortable, errorMessage } from '../utils/async'

export interface SelectedModel {
	model_id: string
	json_schema?: Record<string, unknown>
}

// テキストチャット用モデルのみ公式一覧から選ぶ。モデル種別の省略時はLLM。
export const models = prebuiltAppConfig.model_list.filter(
	/** 埋め込み専用・画像入力用モデルをこの画面の選択肢から除外する。 */
	(model) => (model.model_type ?? ModelType.LLM) === ModelType.LLM,
)

export type ModelStatus = 'idle' | 'loading' | 'ready' | 'error'

export interface LoadedModel {
	engine: WebWorkerMLCEngine
	model: SelectedModel
	signal: AbortSignal
	running: boolean
}

interface Resources {
	worker: Worker
	controller: AbortController
	engine: WebWorkerMLCEngine | null
	disposed: boolean
}

/** GPU資源を解放してからWorkerを終了する。応答不能時も5秒で終了する。 */
async function dispose(resources: Resources): Promise<void> {
	if (resources.disposed) return
	resources.disposed = true
	resources.controller.abort(new Error('モデルのWorkerを終了しました。'))
	let timer: ReturnType<typeof setTimeout> | undefined
	try {
		if (resources.engine) {
			resources.engine.interruptGenerate()
			await Promise.race([
				resources.engine.unload(),
				new Promise<void>((resolve) => { timer = setTimeout(resolve, 5000) }),
			])
		}
	} catch {
		// 解放APIが失敗してもWorker終了による資源回収は必ず実行する。
	} finally {
		clearTimeout(timer)
		resources.worker.terminate()
	}
}

/** Workerの所有権を管理する。自動ダウンロードやウォームアップ推論は行わない。 */
export function useModelLoader() {
	const [status, setStatus] = useState<ModelStatus>('idle')
	const [loadedModel, setLoadedModel] = useState<LoadedModel | null>(null)
	const [progress, setProgress] = useState(0)
	const [progressText, setProgressText] = useState('')
	const [error, setError] = useState<string | null>(null)
	const resourcesRef = useRef<Resources | null>(null)
	const loadedRef = useRef<LoadedModel | null>(null)
	const loadingRef = useRef(false)
	const mountedRef = useRef(false)

	useEffect(() => {
		mountedRef.current = true
		return () => {
			mountedRef.current = false
			const resources = resourcesRef.current
			resourcesRef.current = null
			loadedRef.current = null
			if (resources) void dispose(resources)
		}
	}, [])

	/** 同じmodel_idなら再利用し、切替時は旧モデルを解放してから読み込む。 */
	const load = useCallback(async (model: SelectedModel | null) => {
		if (!model || !mountedRef.current || loadingRef.current || loadedRef.current?.running) return
		if (loadedRef.current?.model.model_id === model.model_id) return
		loadingRef.current = true
		setStatus('loading')
		setError(null)
		setProgress(0)
		setProgressText('モデルの読込を準備しています。')
		const previous = resourcesRef.current
		resourcesRef.current = null
		loadedRef.current = null
		setLoadedModel(null)
		let resources: Resources | null = null

		try {
			if (previous) await dispose(previous)
			if (!mountedRef.current) return
			if (!window.isSecureContext || !('gpu' in navigator)) {
				throw new Error('WebGPU対応ブラウザで、localhostまたはHTTPSから開いてください。')
			}
			const snapshot = structuredClone(model)
			const { CreateWebWorkerMLCEngine } = await import('@mlc-ai/web-llm')
			if (!mountedRef.current) return
			const worker = new Worker(new URL('../workers/webllm.worker.ts', import.meta.url), { type: 'module' })
			const current: Resources = { worker, controller: new AbortController(), engine: null, disposed: false }
			resources = current
			resourcesRef.current = current

			/** Worker異常終了時に未完了の読込・推論を解除する。 */
			const onWorkerError = () => {
				const failure = new Error('モデルのWorkerでエラーが発生しました。再度読み込んでください。')
				current.controller.abort(failure)
				if (mountedRef.current && resourcesRef.current === current) {
					loadedRef.current = null
					setLoadedModel(null)
					setError(failure.message)
					setStatus('error')
				}
				void dispose(current)
			}
			worker.addEventListener('error', onWorkerError)
			worker.addEventListener('messageerror', onWorkerError)

			// appConfigを渡さず、WebLLM内蔵の公式モデル設定で読み込む。
			const engine = await abortable(CreateWebWorkerMLCEngine(worker, snapshot.model_id, {
				/** 古いWorkerからの進捗通知は画面へ反映しない。 */
				initProgressCallback: (report) => {
					if (!mountedRef.current || current.controller.signal.aborted) return
					setProgress(Number.isFinite(report.progress) ? Math.min(1, Math.max(0, report.progress)) : 0)
					setProgressText(report.text)
				},
			}), current.controller.signal)
			current.engine = engine
			if (!mountedRef.current || current.controller.signal.aborted) {
				await dispose(current)
				return
			}
			const loaded: LoadedModel = { engine, model: snapshot, signal: current.controller.signal, running: false }
			loadedRef.current = loaded
			setLoadedModel(loaded)
			setProgress(1)
			setProgressText('モデルの読込が完了しました。')
			setStatus('ready')
		} catch (cause) {
			if (resources) await dispose(resources)
			resourcesRef.current = null
			loadedRef.current = null
			if (mountedRef.current) {
				setLoadedModel(null)
				setError(errorMessage(cause))
				setProgressText('モデルの読込に失敗しました。')
				setStatus('error')
			}
		} finally {
			loadingRef.current = false
		}
	}, [])

	return { status, loadedModel, progressPct: Math.round(progress * 100), progressText, error, load }
}
