// Generated by GitHub Copilot - Sep-26-2026
import { WebWorkerMLCEngineHandler } from '@mlc-ai/web-llm'

const handler = new WebWorkerMLCEngineHandler()
/** モデルの読込・推論をメインスレッドから分離する。 */
self.onmessage = (event: MessageEvent) => handler.onmessage(event)