// Generated by GitHub Copilot - Sep-28-2026
import {
  Alert,
  Box,
  Button,
  Chip,
  Container,
  LinearProgress,
  MenuItem,
  Paper,
  Stack,
  TextField,
  Typography,
} from "@mui/material";
import { useMemo, useState, type FormEvent } from "react";
import { useLLMCompletion } from "../hooks/useLLMCompletion";
import { models, useModelLoader } from "../hooks/useModelLoader";

/** 入力と結果を等幅に配置する。生成テキストはHTMLとして解釈せず安全に表示する。 */
export default function HomeCompoentns() {
  const [selectedModelId, setSelectedModelId] = useState("");
  const [systemPrompt, setSystemPrompt] = useState("");
  const [message, setMessage] = useState("");
  const [jsonSchema, setJsonSchema] = useState("");
  const {
    status,
    loadedModel,
    progressPct,
    progressText,
    error: loadError,
    load,
  } = useModelLoader();
  const {
    answer,
    logs,
    isRunning,
    error: completionError,
    complete,
    clearLogs,
  } = useLLMCompletion();
  const selectedModel =
    models.find((model) => model.model_id === selectedModelId) ?? null;
  const sameModel =
    selectedModel !== null &&
    selectedModel.model_id === loadedModel?.model.model_id;
  const busy = status === "loading" || isRunning;
  const logText = useMemo(() => logs.map((log) => JSON.stringify(log)).join("\n"), [logs]);

  /** 読込と推論を分離し、読込完了後も自動で推論を始めない。 */
  const handleSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (busy || !selectedModel) return;
    if (sameModel) {
      void complete(loadedModel, selectedModel, systemPrompt, message, jsonSchema);
    } else {
      void load(selectedModel);
    }
  };

  return (
    <Box sx={{ minHeight: "100vh", bgcolor: "grey.50" }}>
      <Container component="main" maxWidth="xl" sx={{ py: 2 }}>
        <Box
          sx={{
            display: "grid",
            gridTemplateColumns: {
              xs: "minmax(0, 1fr)",
              md: "repeat(2, minmax(0, 1fr))",
            },
            gap: 2,
          }}
        >
          <Stack
            component="form"
            onSubmit={handleSubmit}
            spacing={1}
            sx={{ minWidth: 0 }}
          >
            <Typography component="h2" variant="subtitle2">
              入力
            </Typography>
            <Stack
              component={Paper}
              variant="outlined"
              spacing={2}
              sx={{
                p: 2,
                flex: 1,
                '& .MuiInputBase-root, & .MuiInputLabel-root': { typography: 'body2' },
              }}
            >
              <TextField
                select
                fullWidth
                label="WebLLM選択"
                value={selectedModelId}
                onChange={(event) => setSelectedModelId(event.target.value)}
                disabled={busy}
              >
                <MenuItem value="" sx={{ typography: 'body2' }}>モデルを選択</MenuItem>
                {models.map((model) => (
                  <MenuItem key={model.model_id} value={model.model_id} sx={{ typography: 'body2' }}>
                    {model.model_id}
                  </MenuItem>
                ))}
              </TextField>

              <TextField
                label="システムプロンプト"
                multiline
                rows={6}
                fullWidth
                value={systemPrompt}
                onChange={(event) => setSystemPrompt(event.target.value)}
                placeholder="回答の方針や役割を入力してください。"
              />
              <TextField
                label="メッセージ"
                multiline
                rows={6}
                fullWidth
                value={message}
                onChange={(event) => setMessage(event.target.value)}
                placeholder="モデルに渡す文章や質問を入力してください。"
              />
              <TextField
                label="構造化出力のJSONスキーマ"
                multiline
                rows={6}
                fullWidth
                value={jsonSchema}
                onChange={(event) => setJsonSchema(event.target.value)}
                placeholder={'{"type":"object","properties":{"answer":{"type":"string"}},"required":["answer"]}'}
                helperText="任意入力。空欄の場合は構造化出力を指定しません。"
              />

              <Button
                type="submit"
                variant="contained"
                fullWidth
                disabled={!selectedModel || busy}
              >
                {status === "loading"
                  ? "読込中…"
                  : isRunning
                    ? "実行中…"
                    : sameModel
                      ? "実行"
                      : "読込"}
              </Button>

              <Stack spacing={1}>
                {loadedModel && (
                  <Chip
                    variant="outlined"
                    color="success"
                    label={`読込済み: ${loadedModel.model.model_id}`}
                    sx={{ alignSelf: "flex-start", maxWidth: "100%" }}
                  />
                )}
                {status === "loading" && (
                  <>
                    <LinearProgress
                      variant="determinate"
                      value={progressPct}
                      aria-label="モデルの読込進捗"
                    />
                    <Typography variant="body2">{progressPct}%</Typography>
                    <Typography
                      role="status"
                      variant="body2"
                      color="textSecondary"
                      sx={{ overflowWrap: "anywhere" }}
                    >
                      {progressText}
                    </Typography>
                  </>
                )}
                {loadError && (
                  <Alert severity="error" sx={{ overflowWrap: "anywhere" }}>
                    {loadError}
                  </Alert>
                )}
                {completionError && (
                  <Alert severity="error" sx={{ overflowWrap: "anywhere" }}>
                    {completionError}
                  </Alert>
                )}
              </Stack>
            </Stack>
          </Stack>

            <Stack component="section" spacing={1} sx={{ minWidth: 0 }}>
              <Typography component="h2" variant="subtitle2">
                出力
              </Typography>
              <Paper variant="outlined" sx={{ p: 2, flex: 1 }}>
              <Typography
                component="pre"
                variant="body2"
                role="region"
                aria-label="回答テキスト"
                aria-busy={isRunning}
                tabIndex={0}
                sx={{
                  m: 0,
                  minHeight: 250,
                  maxHeight: 550,
                  overflow: "auto",
                  whiteSpace: "pre-wrap",
                  overflowWrap: "anywhere",
                  "&:focus-visible": {
                    outline: "3px solid",
                    outlineColor: "primary.main",
                    outlineOffset: 4,
                  },
                }}
              >
                {answer ||
                  (isRunning
                    ? "回答を生成しています…"
                    : "ここに回答が表示されます。")}
              </Typography>
              </Paper>
            </Stack>
        </Box>

            <Stack component="section" spacing={1} sx={{ mt: 2 }}>
              <Stack direction="row" spacing={1} sx={{ alignItems: "baseline" }}>
                <Typography component="h2" variant="subtitle2">
                  ログ
                </Typography>
                <Button type="button" size="small" onClick={clearLogs}>
                  クリア
                </Button>
              </Stack>
              <Paper variant="outlined" sx={{ p: 2 }}>
              <Typography
                component="pre"
                variant="caption"
                role="region"
                aria-label="実行ログJSON"
                tabIndex={0}
                sx={{
                  m: 0,
                  minHeight: 70,
                  maxHeight: 200,
                  overflow: "auto",
                  whiteSpace: "pre",
                  "&:focus-visible": {
                    outline: "3px solid",
                    outlineColor: "primary.main",
                    outlineOffset: 4,
                  },
                }}
              >
                {logText}
              </Typography>
              </Paper>
            </Stack>

        <Box
          component="aside"
          sx={{ mt: 2, color: "text.secondary" }}
        >
          <Typography component="p" variant="caption">
		モデルファイルのキャッシュの削除方法（Chrome／Edge）
          </Typography>
          <Typography component="p" variant="caption">
            このアプリを開き、F12 → Application → Storage 内の Cache Storageを開いてください。
            WebLLM関連のキャッシュを右クリック → Deleteで削除し、ページを再読み込みしてください。
            次回のモデル読込時に再ダウンロードが発生します。
          </Typography>
        </Box>
      </Container>
    </Box>
  );
}
