// Generated by GitHub Copilot - Sep-26-2026
/** エラーをテキストとして扱い、HTMLとして解釈しない。 */
export function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error)
}

/** Worker停止時にも待機を解除し、完了後はイベントリスナーを解放する。 */
export function abortable<T>(operation: Promise<T>, signal: AbortSignal): Promise<T> {
  return new Promise<T>((resolve, reject) => {
    /** Workerの終了理由を呼出元へ伝える。 */
    const onAbort = () => reject(signal.reason ?? new Error('処理を中断しました。'))
    signal.addEventListener('abort', onAbort, { once: true })
    if (signal.aborted) onAbort()
    operation.then(resolve, reject).finally(() => signal.removeEventListener('abort', onAbort))
  })
}